#! /usr/bin/env bash

###################################################
#
#  Copyright (C) 2009 Stephan Tetzel <zefanja@freenet.de> and Shutter Team
#
#  This file is part of Shutter.
#
#  Shutter is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Shutter is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Shutter; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###################################################

TEXTDOMAIN=shutter-plugins
TEXTDOMAINDIR=$SHUTTER_INTL
PLUGIN_NAME=$"reflection"
PLUGIN_SORT=$"effect"
PLUGIN_TIP=$"applies a simple reflection effect"
PLUGIN_EXT="image/png"

if [[ "${1}" = "name" ]];then
   	echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    echo "shell"
    exit 0
fi

FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"
#FILEYTPE="${4}"
#GEO="${2}x${3}"

convert "${FILE}" -flip unten.png
convert  xc:"#9E9E9E" -size "${WIDTH}"x512 xc:black -size "${WIDTH}"x128 gradient:"#9E9E9E"-black +swap -append overlap.png
composite overlap.png unten.png -compose CopyOpacity unten.png
convert "${FILE}" unten.png -extent $((${WIDTH}))x$(($HEIGHT+128)) -background none -geometry +0+$(($HEIGHT+10)) -composite "${FILE}"

#cleanup
rm unten.png overlap.png

exit 0
