#!/bin/bash
#jigsaw piece 2
#gscrot-plugin

. gettext.sh

TEXTDOMAIN=gscrot-plugins-bash
TEXTDOMAINDIR=$GSCROT_INTL
PLUGIN_NAME="jigsaw piece 2"
PLUGIN_SORT="effect"
PLUGIN_TIP="cut a jigsaw piece out of the picture"
PLUGIN_EXT="png"

if [[ "${1}" = "name" ]];then
    gettext "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    gettext "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    gettext "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    gettext "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    gettext "shell"
    exit 0
fi

FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"
FILEYTPE="${4}"
GEO="${2}x${3}"
PIECE="$GSCROT_ROOT/share/gscrot/resources/system/plugins/bash/gspjigsaw2/gspjigsaw_2.png"
JIGSAW="$GSCROT_ROOT/share/gscrot/resources/system/plugins/bash/gspjigsaw2/jigsaw"

convert "${PIECE}" -resize "${GEO}" \
-background none /tmp/jigsaw_cnr_tmpl.png

${JIGSAW} -t 3 -s  -r 10 \
"${FILE}" /tmp/jigsaw_cnr_tmpl.png "${FILE}"

NEW_GEO=$(identify -format %wx%h "${FILE}")

convert "${FILE}" -gravity center -crop ${NEW_GEO} +repage \
"${FILE}"

rm -f /tmp/jigsaw_cnr_tmpl.png


exit 0
