#!/bin/bash 
#GScrot PDF Export 
#gscrot-plugin  

TEXTDOMAIN=gscrot-plugins-bash 
TEXTDOMAINDIR=$GSCROT_INTL
PLUGIN_NAME=$"pdf export" 
PLUGIN_SORT=$"tool" 
PLUGIN_TIP=$"export your screenshot to pdf" 
PLUGIN_EXT="png, jpeg"  

if [[ "${1}" = "name" ]];then
    echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    echo "shell"
    exit 0
fi


FILE="${1}"
#WIDTH="${2}"
#HEIGHT="${3}"
#FILEYTPE="${4}"
#GEO="${2}x${3}"

convert "$FILE" "$FILE.pdf"  

if [[ -e /usr/bin/gnome-open ]];then
	gnome-open "$FILE.pdf"
fi
 
exit 0