#!/bin/bash
#hard shadow
#gscrot-plugin

. gettext.sh

TEXTDOMAIN=gscrot-plugins-bash
TEXTDOMAINDIR=$GSCROT_INTL
PLUGIN_NAME="hard shadow"
PLUGIN_SORT="effect"
PLUGIN_TIP="a black hard shadow on transparent background"
PLUGIN_EXT="png"

if [[ "${1}" = "name" ]];then
    gettext "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    gettext "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    gettext "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    gettext "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    gettext "shell"
    exit 0
fi

FILE="${1}"
#WIDTH="${2}"
#HEIGHT="${3}"
#FILEYTPE="${4}"
#GEO="${2}x${3}"

convert "${FILE}" \( +clone -background black  -shadow 80x3+5+5 \) \
+swap -background none -mosaic +repage "${FILE}"
       
exit 0
