#!/bin/sh
set -e

if [ "$1" != configure ]; then
	exit 0
fi

unud=/var/lib/update-notifier/user.d

if [ -d $unud ]; then
	cp -f /usr/share/shutter/update-notifier-shutter \
	    "$unud/update-notifier-shutter"
fi

if [ -x /usr/sbin/update-app-install ]; then               
           update-app-install || true              
fi

