#! /usr/bin/env bash

###################################################
#
#  Copyright (C) 2008-2012 Mario Kemper <mario.kemper@googlemail.com> and Shutter Team
#
#  This file is part of Shutter.
#
#  Shutter is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Shutter is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Shutter; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
###################################################

TEXTDOMAIN=shutter-plugins
TEXTDOMAINDIR=$SHUTTER_INTL
PLUGIN_NAME=$"Shutter Branding"
PLUGIN_SORT=$"Effect"
PLUGIN_TIP=$"Turn the image into a polaroid one with the Shutter logo and a subtitle added"
PLUGIN_EXT="image/png"

if [[ "${1}" = "name" ]];then
   	echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
fi

FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"
FILEYTPE="${4}"
INTL_PATH="${5}"
GEO="${2}x${3}"
SHORTNAME=$(basename "${1}")
LOGO="$SHUTTER_ROOT/share/shutter/resources/system/plugins/shell/spaddlogo/shutter_branding.png"

mogrify -resize 480x400\> \
-bordercolor white -border 22x22 \
-gravity south -annotate 0 "${SHORTNAME}" \
-bordercolor white -border 4x4 \
"${FILE}"

convert "${FILE}" "${LOGO}" \
-background none -mosaic +repage "${FILE}"

convert "${FILE}" \( +clone -background black  -shadow 80x3+5+5 \) \
+swap -background none -mosaic +repage -rotate -4 \
"${FILE}"

exit 0
