#!/bin/bash
#polaroid
#gscrot-plugin

TEXTDOMAIN=gscrot-plugins-bash
TEXTDOMAINDIR=$GSCROT_INTL
PLUGIN_NAME=$"polaroid"
PLUGIN_SORT=$"effect"
PLUGIN_TIP=$"polaroid effect whith white border and black shadow"
PLUGIN_EXT="png"

if [[ "${1}" = "name" ]];then
    echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    echo "shell"
    exit 0
fi

FILE="${1}"
#WIDTH="${2}"
#HEIGHT="${3}"
#FILEYTPE="${4}"
#GEO="${2}x${3}"

convert "${FILE}" -resize 250x250\> \
-bordercolor white -border 8x8 \
-bordercolor gray -border 1x1 \
\( +clone -background black  -shadow 80x3+5+5 \) \
+swap -background none -mosaic +repage -rotate -4 "${FILE}"

exit 0
