#!/bin/bash
#grayscale
#gscrot-plugin

TEXTDOMAIN=gscrot-plugins-bash
TEXTDOMAINDIR=/usr/share/locale 
PLUGIN_NAME=$"grayscale"
PLUGIN_SORT=$"effect"
PLUGIN_TIP=$"256 color grayscale"
PLUGIN_EXT="png,jpeg"

if [[ "${1}" = "name" ]];then
    echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    echo "shell"
    exit 0
fi

FILE="${1}"
#WIDTH="${2}"
#HEIGHT="${3}"
#FILEYTPE="${4}"
INTL_PATH="${5}"
#GEO="${2}x${3}"

convert "${FILE}" -colorspace Gray "${FILE}"
          
exit 0
