#!/bin/bash
#jigsaw piece 2
#shutter-plugin


TEXTDOMAIN=shutter-plugins-bash
TEXTDOMAINDIR=$SHUTTER_INTL
PLUGIN_NAME=$"jigsaw piece 2"
PLUGIN_SORT=$"effect"
PLUGIN_TIP=$"cut a jigsaw piece out of the picture"
PLUGIN_EXT="image/png"

if [[ "${1}" = "name" ]];then
   	echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
elif [[ "${1}" = "lang" ]];then
    echo "shell"
    exit 0
fi

FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"
FILEYTPE="${4}"
GEO="${2}x${3}"
PIECE="$SHUTTER_ROOT/share/shutter/resources/system/plugins/bash/spjigsaw2/spjigsaw_2.png"
JIGSAW="$SHUTTER_ROOT/share/shutter/resources/system/plugins/bash/spjigsaw2/jigsaw"

convert "${PIECE}" -resize "${GEO}" \
-background none /tmp/jigsaw_cnr_tmpl.png

${JIGSAW} -t 3 -s  -r 10 \
"${FILE}" /tmp/jigsaw_cnr_tmpl.png "${FILE}"

NEW_GEO=$(identify -format %wx%h "${FILE}")

convert "${FILE}" -gravity center -crop ${NEW_GEO} +repage \
"${FILE}"

rm -f /tmp/jigsaw_cnr_tmpl.png


exit 0
